/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import autogenerated.entities.Signature;
import business.Categorizer;
import db.daos.ProductDAO;
import enums.DbMessageEnum;
import enums.FileNameEnums;
import enums.ProductTypeEnums;
import java.util.List;
import jaxb.JAXBUnmarshaller;

/**
 *
 * @author Hoang Pham
 */
public class DbAccessor {

    private static final int headphoneTypeId = ProductTypeEnums.HEADPHONES.getTypeId();
    private static final int iemTypeId = ProductTypeEnums.IEMS_INEARS.getTypeId();

    public boolean insertHeadphones() {
        boolean allSuccess = true;
        JAXBUnmarshaller jAXBUnmarshaller = new JAXBUnmarshaller();
        List<Signature> list = jAXBUnmarshaller.getHeadphones(FileNameEnums.FINAL_SIGNATURES_XML.getFileName());
        ProductDAO dao = new ProductDAO();

        int categoryId;
        int errorCount = 0;
        for (Signature signature : list) {
            Categorizer categorizer = new Categorizer();
            categoryId = categorizer.getCategoryOfSignature(signature.getName());
            String message = dao.insertSignature(signature, categoryId, headphoneTypeId);
            if (!message.equals(DbMessageEnum.SUCCESS.getMessage())) {
                System.out.println(message);
                allSuccess = false;
                errorCount++;
            }
        }
        if (errorCount == list.size()) {
            System.out.println("!!! Failed to insert any item");
        } else if (!allSuccess) {
            System.out.println("!!! Some item(s) were failed to be inserted");
        }
        return allSuccess;
    }
    
    public boolean insertIems() {
        boolean allSuccess = true;
        JAXBUnmarshaller jAXBUnmarshaller = new JAXBUnmarshaller();
        List<Signature> list = jAXBUnmarshaller.getIems(FileNameEnums.FINAL_SIGNATURES_XML.getFileName());
        ProductDAO dao = new ProductDAO();

        int categoryId;
        int errorCount = 0;
        for (Signature signature : list) {
            Categorizer categorizer = new Categorizer();
            categoryId = categorizer.getCategoryOfSignature(signature.getName());
            String message = dao.insertSignature(signature, categoryId, iemTypeId);
            if (!message.equals(DbMessageEnum.SUCCESS.getMessage())) {
                System.out.println(message);
                allSuccess = false;
                errorCount++;
            }
        }
        if (errorCount == list.size()) {
            System.out.println("!!! Failed to insert any item");
        } else if (!allSuccess) {
            System.out.println("!!! Some item(s) were failed to be inserted");
        }
        return allSuccess;
    }
}
