/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import autogenerated.entities.Signature;
import business.Categorizer;
import db.daos.ProductDAO;
import enums.FileNameEnums;
import java.util.List;
import jaxb.JAXBUnmarshaller;

/**
 *
 * @author Hoang Pham
 */
public class TestMain {

    public static void main(String[] args) {
//        String url = UrlEnums.CRINACLE_RANKINGS.getUrl();
//        String fileName = "signatureLinks.xml";
//        String xslPath = "src/signatureLinksTransformer.xsl";

//  Download html            
//        WebPageDownloader webPageDownloader = new WebPageDownloader();
//        webPageDownloader.writeSignaturesLinkList2XmlFileFromInputStream(UrlEnums.CRINACLE_RANKINGS.getUrl(), "src\\demo.xml");
//        downloadWebPage.writeProductXmlFileFromInputStream(url, fileName);
//        downloadWebPage.writeSignatureXmlFileFromInputStream(url, fileName);
//        downloadWebPage.writeProductsLinkListXmlFileFromInputStream(url, fileName);
//        downloadWebPage.writeSignaturesLinkListXmlFileFromInputStream(url, fileName);
//  Check well-formed
//        MyXMLParser parser = new MyXMLParser();
//        parser.checkWellFormedXml("demo.xml");
//        if (parser.parseSignatureXml(fileName, "parsedXml.xml")) {
//            //  If well-formed, transform to working xml file  
//            XMLTransformer transformer = new XMLTransformer();
//            transformer.transform("signatureLinks.xml", "linksXml.xml", xslPath);
//        }
//        SignatureCrawler crawler = new SignatureCrawler();
//        crawler.demo();
//        MyXMLParser parser = new MyXMLParser();
//        ArrayList<String> links = (ArrayList<String>) parser.getSignatureLinks(FileNameEnums.FINAL_SIGNATURES_LINK_XML.getFileName());
//        webPageDownloader.writeSignature2XmlFileFromInputStream(links, "hoang.xml");
//        DbAccessor dbAccessor = new DbAccessor();
//        ProductEntity entity = new ProductEntity();
//        dbAccessor.insertProduct(entity);
//        MyXMLParser parser = new MyXMLParser();
//        parser.checkWellFormedXml("demo.xml");
//        List<ProductEntity> list = parser.mapSignatureXml2Objects("demo.xml");
//        System.out.println("List size: " + list.size());
//        System.out.println(list.toString());
//        JAXBUnmarshaller jAXBUnmarshaller = new JAXBUnmarshaller();
//        List<Signature> list = jAXBUnmarshaller.getHeadphones(FileNameEnums.FINAL_SIGNATURES_XML.getFileName());
//        ProductDAO dbAccessor = new ProductDAO();
//        Signature signature = list.get(0);
//        Categorizer categorizer = new Categorizer();
//        int categoryId = categorizer.getCategoryOfSignature(signature.getName());
//        dbAccessor.insertSignature(signature, categoryId);
    }
}
