/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaxb;

import autogenerated.entities.Signature;
import autogenerated.entities.Signatures;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

/**
 *
 * @author Hoang Pham
 */
public class JAXBUnmarshaller {

    public static void main(String[] args) {
        try {
            // TODO code application logic here
            JAXBContext jc = JAXBContext.newInstance(Signatures.class);
            Unmarshaller um = jc.createUnmarshaller();
            File f = new File("demo.xml");
            Signatures signatures = (Signatures) um.unmarshal(f);
            List<Signature> headphones = signatures.getHeadphones().getSignature();
            for (Signature iem : headphones) {
                System.out.println(iem.getModel());
            }
        } catch (JAXBException ex) {
            System.out.println("Failed to unmarshall from demo.xml: " + ex.getMessage());
        }
    }

    public List<Signature> getHeadphones(String xmlFile) {
        List<Signature> list = new ArrayList<>();
        try {
            JAXBContext jaxb = JAXBContext.newInstance(Signatures.class);
            Unmarshaller unmarshaller = jaxb.createUnmarshaller();
            File file = new File(xmlFile);
            Signatures signatures = (Signatures) unmarshaller.unmarshal(file);
            return signatures.getHeadphones().getSignature();
        } catch (Exception e) {
            System.out.println("Failed to unmarshall from " + xmlFile
                    + ", error: " + e.getMessage());
        }
        return list;
    }
    
     public List<Signature> getIems(String xmlFile) {
        List<Signature> list = new ArrayList<>();
        try {
            JAXBContext jaxb = JAXBContext.newInstance(Signatures.class);
            Unmarshaller unmarshaller = jaxb.createUnmarshaller();
            File file = new File(xmlFile);
            Signatures signatures = (Signatures) unmarshaller.unmarshal(file);
            return signatures.getIems().getSignature();
        } catch (Exception e) {
            System.out.println("Failed to unmarshall from " + xmlFile
                    + ", error: " + e.getMessage());
        }
        return list;
    }
}
